#!/bin/bash








sed 's/\r//' POSCAR > POSCAR_TEMP



type_line=$(sed -n '6p' POSCAR_TEMP)
type_array=($type_line)
type_size=${#type_array[*]}



number_line=$(sed -n '7p' POSCAR_TEMP)
number_array=($number_line)
number_size=${#number_array[*]}






#Create AUGMENTER file
for (( i=0; i<$type_size; i++ ));
do
        cd ./${type_array[i]}
                for(( j=0; j<${number_array[i]}; j++ ))
                do
#########################################################








#grep command returns the line with the aug occ: [ string string atomNumber #augmentations ]
aug_line=$(grep "augmentation occupancies" CHGCAR)
#Parse string into useful array
aug_array=($aug_line)

#use last element of array to find number of trailing lines after grep hit that contain aug occ
end_line=$(( ${aug_array[3]}/5 ))

#augmentations are stored in 5 columns, leftovers will be put in partially filed line
if (( ${aug_array[3]}%5 != 0 ));then
	end_line=$(( $end_line+1 ))
fi

echo "${aug_array[0]} ${aug_array[1]} ${aug_array[2]} ${aug_array[3]}" >> ../AUGMENTER
grep -A $end_line "augmentation occupancies" CHGCAR | tail -$end_line >> ../AUGMENTER

##########################################################



                done
        cd ..
done

